import itertools
load("gl.sage")
load("utils.sage")
load("hermi.sage")
load("jordan.sage")
load("Lfunc.sage")
load("quadlatticeclass.sage")
load("hermilatticeclass.sage") 
load("gllatticeclass.sage") 

if 'first_run' not in locals():
    first_run = True

if first_run:
    orb_int_unitary_db = {}
    hermi_latt_db = {}  
    gl_latt_db = {}
    first_run = False

def setup_local_algebraic_data(p, cyclo_order, D_K):
    """
    Extracts local algebraic data at a prime p from the global fields (E_i/F_i) 
    and packages them into a dictionary required for local invariant computations.

    INPUT:
        p           : integer; the rational prime.
        cyclo_order : integer; the cyclotomic order m (tame part).
        D_K         : integer; the discriminant of the global quadratic field.

    OUTPUT:
        dict: A dictionary containing local algebraic structures and functions:
            - 'q', 'unif', 'E', 'OE', 'residue_field', 'conj', 'val_func',
            - 'trace_func', 'basis', 'd', 'e', 'notnorm'.
    """
    block_data = block_fields_unitary(cyclo_order, D_K, False)
    Ei = block_data["Ei"]
    Fi = block_data["Fi"]
    embed_F_to_E = block_data["embed_F_to_E"]
    
    if Fi == QQ:
        q = p
        e_ram = 1
        residue_field = GF(p)
        P_Fi = p
        unif = p
        p_in_E = Ei.ideal(p)
    else:
        P_Fi = Fi.primes_above(p)[0]
        q = P_Fi.norm()
        e_ram = P_Fi.ramification_index()
        residue_field = Fi.residue_field(P_Fi)
        gens_F = P_Fi.gens_reduced()
        P_Fi_sq = P_Fi**2
        unif = None
        for g in gens_F:
            if g != 0 and g not in P_Fi_sq:
                unif = Fi(g)
                break
        p_in_E = Ei.ideal([embed_F_to_E(g) for g in P_Fi.gens()])
        
    factored_primes = list(p_in_E.factor())
    P_Ei = factored_primes[0][0]
    
    diff_Ei = Ei.different().valuation(P_Ei)
    if Fi == QQ:
        d = diff_Ei
    else:
        diff_Fi_lifted = Ei.ideal([embed_F_to_E(g) for g in Fi.different().gens()]).valuation(P_Ei)
        d = diff_Ei - diff_Fi_lifted

    conj = None
    for aut in Ei.automorphisms():
        if aut(Ei.gen()) != Ei.gen():
            if Fi == QQ or all(aut(embed_F_to_E(g)) == embed_F_to_E(g) for g in Fi.gens()):
                conj = aut
                break
    if conj is None:
        conj = Ei.complex_conjugation()

    def val_func(x):
        return Ei.ideal(x).valuation(P_Ei) if x != 0 else infinity

    def trace_func(x):
        return x + conj(x)
        
    alpha = Ei.gen()
    if conj(alpha) == alpha:
        for g in Ei.gens():
            if conj(g) != g:
                alpha = g
                break
    basis = [Ei(1), alpha]

    notnorm = None
    if p != 2 and len(factored_primes) == 1 and factored_primes[0][1] > 1:
        if Fi == QQ:
            for x in range(1, p):
                if not residue_field(x).is_square():
                    notnorm = QQ(x)
                    break
        else:
            for x in Fi.ring_of_integers():
                if x not in P_Fi:
                    x_mod = residue_field(x)
                    if not x_mod.is_square():
                        notnorm = Fi(x)
                        break

    return {
        'q': q, 'unif': unif, 'E': Ei, 'F': Fi, 'OE': Ei.ring_of_integers(), 
        'residue_field': residue_field, 'conj': conj, 'val_func': val_func, 
        'trace_func': trace_func, 'basis': basis, 'd': d, 'e': e_ram,
        'notnorm': notnorm, 'embed_F_to_E': embed_F_to_E, 'p_ideal': P_Fi
    }

def enum_with_inv_hermi(p, m, mult, maxpower, D_K, alg_data):
    """
    Enumerates Hermitian lattices using generalized algebraic data.

    INPUT:
        p        : integer; the prime number.
        m        : integer; cyclotomic order (tame part).
        mult     : integer; multiplicity.
        maxpower : integer; maximum power parameter for enumeration.
        D_K      : integer; discriminant of the global quadratic field.
        alg_data : dict; dictionary containing local algebraic structures 
                   generated by setup_local_algebraic_data.

    OUTPUT:
        dict: A dictionary mapping invariant tuples (Jordan types) to lists of lattice objects.
    """
    Lattices = enum_hermi(p, m, D_K, mult, maxpower, alg_data)
    
    result = {}
    for B in Lattices:
        disc_isnorm = Mod(B[0], 2)
        lattice = B[1]
        if disc_isnorm not in result:
            result[disc_isnorm] = []
        result[disc_isnorm].append(lattice)
    return result

def orb_int_gl(args, Fi=None):
    """
    Engine bridge for General Linear (GL) orbital integrals.

    INPUT:
        args : list of tuples; each tuple is (p, exponent, multiplicity, max_power_param).
        Fi   : NumberField (Optional); the base totally real field.

    OUTPUT:
        list of tuples: Returns a list of (partition, value) pairs.
    """
    results = []
    for p, exponent, multiplicity, max_power_param in args:
        if Fi is not None and Fi != QQ:
            P_Fi = Fi.primes_above(p)[0]
            qv = P_Fi.norm()
        else:
            qv = p
            
        if exponent == 0:
            e = 1
        else:
            e = p**(exponent - 1) * (p - 1)
            
        max_slots = e * max_power_param
        parts = enum_partitions(multiplicity, max_slots)
        for I in parts:
            val = gl_mass_local_term(qv, I)
            results.append((tuple(I), val))
    return results

def orb_int_unitary(args_list, hermi_latt_db, D_K):
    """
    Generator that yields the total orbital integral values for unitary cases.

    INPUT:
        args_list     : list of tuples; arguments containing (p, cyclo_order, jordan_blocks, partition_tup).
        hermi_latt_db : dict; database of precomputed Hermitian lattices.
        D_K           : integer; discriminant parameter of the global field.

    OUTPUT:
        generator: Yields tuples of (args, total_orbital_integral).
    """
    for args in args_list:
        p, cyclo_order, jordan_blocks, partition_tup = args
        total_orbital_integral = 1
        max_power_param = len(jordan_blocks) - 1
        for i, (exponent, multiplicity) in enumerate(jordan_blocks):
            complete_order = cyclo_order * (p**exponent)
            lattice_query_key = (p, complete_order, multiplicity, max_power_param, D_K)
            target_partition = partition_tup[i]
            matched_lattices = hermi_latt_db[lattice_query_key][target_partition]
            block_sum = QQ(0)
            for latt in matched_lattices:
                block_sum += QQ(latt.mass_local_term)
            
            total_orbital_integral *= block_sum
            
        yield args, total_orbital_integral

def update_orb_int_unitary_db(n, primes_list, D_K, pretend=False, verbose=False):
    """
    Populate orb_int_unitary_db with all local orbital integral data needed
    for elliptic finite-order stable conjugacy classes in the unitary setting.

    INPUT:
        n           : integer; total size (default global setting U(n/2,n/2))
        primes_list : list of rational primes at which local data may be needed
        D_K         : integer; discriminant parameter for E = Q(sqrt(D_K))
        pretend     : boolean; if True, only print what would be computed, do not store
        verbose     : boolean; print progress

    OUTPUT:
        None (updates the global dictionary orb_int_unitary_db in place)
    """
    
    # Properly pass D_K and verbose to match utils.sage definition
    conj_classes = conjclasses_unitary(n, primes_list, D_K, verbose)
    required_params = {
        (p, cyclo_order, tuple(jordan_blocks))
        for p in primes_list
        for cc in conj_classes
        for cyclo_order, jordan_blocks, _ in tot_ram_sub_conj_classes_unitary(cc, p)
    }

    new_params = [
        param for param in required_params
        if (param[0], param[1], param[2], D_K) not in orb_int_unitary_db
    ]
    num_tasks = len(new_params)
    
    if verbose:
        print("=" * 80)
        print(f"Updating unitary orbital-integral DB for D_K = {D_K}")
        print(f"Number of required local tasks: {num_tasks}")
        print("=" * 80)

    for idx, (p, cyclo_order, jordan_blocks) in enumerate(sorted(new_params), 1):
        db_storage_key = (p, cyclo_order, tuple(jordan_blocks), D_K)
        if verbose:
            print("-" * 80)
            print(f"[{idx}/{num_tasks}] Computing local data for key:")
            print(f"    p = {p}")
            print(f"    cyclo_order = {cyclo_order}")
            print(f"    jordan_blocks = {jordan_blocks}")
            print(f"    D_K = {D_K}")
            
        if pretend:
            continue

        block_data = block_fields_unitary(cyclo_order, D_K, False)
        Ei = block_data["Ei"]
        Fi = block_data["Fi"]
        embed_F_to_E = block_data["embed_F_to_E"]
        
        if Fi == QQ:
            P_Fi = QQ.ideal(p)
            p_in_E = Ei.ideal(p)
        else:
            P_Fi = Fi.primes_above(p)[0]
            p_in_E = Ei.ideal([embed_F_to_E(g) for g in P_Fi.gens()])
            
        is_split = (len(p_in_E.factor()) == 2)
        local_results_map = {}
        max_power_param = len(jordan_blocks) - 1

        # ============================================================
        # GL case (Split)
        # ============================================================
        if is_split:
            primes_v_above_p = [p] if Fi == QQ else Fi.primes_above(p)
            total_density_at_p = QQ(1)
            
            for v in primes_v_above_p:
                if Fi == QQ:
                    ev = 1
                    qv = p
                else:
                    ev = v.ramification_index()
                    qv = p ** v.residue_class_degree()
                
                density_at_v = QQ(1)
                for exponent, multiplicity in jordan_blocks:
                    complete_order = cyclo_order * (p ** exponent)
                    gl_key = (v, complete_order, multiplicity, max_power_param)
                    
                    if gl_key not in gl_latt_db:
                        gl_latt_db[gl_key] = enum_split(p, complete_order, multiplicity, max_power_param, ev, qv)
                    
                    lattices_in_block = gl_latt_db[gl_key]
                    
                    current_block_val = QQ(0)
                    for item in lattices_in_block:
                        latt_obj = item[1]
                        current_block_val += QQ(latt_obj.mass_local_term)
                    
                    density_at_v *= current_block_val
                    
                total_density_at_p *= density_at_v

            if total_density_at_p != 0:
                dummy_inv_key = tuple(Mod(0, 2) for _ in jordan_blocks)
                local_results_map[dummy_inv_key] = total_density_at_p

        # ============================================================
        # Hermitian case (Inert/Ramified)
        # ============================================================
        else:
            alg_data = setup_local_algebraic_data(p, cyclo_order, D_K)
            partition_options_per_block = []

            for exponent, multiplicity in jordan_blocks:
                complete_order = cyclo_order * (p ** exponent)
                hermi_key = (p, complete_order, multiplicity, max_power_param, D_K)

                if hermi_key not in hermi_latt_db:
                    hermi_latt_db[hermi_key] = enum_with_inv_hermi(
                        p, complete_order, multiplicity, max_power_param, D_K, alg_data
                    )

                partition_options_per_block.append(list(hermi_latt_db[hermi_key].keys()))

            for partition_combination in itertools.product(*partition_options_per_block):
                single_arg = (p, cyclo_order, jordan_blocks, partition_combination)
                
                for res_args, density_value in orb_int_unitary([single_arg], hermi_latt_db, D_K):
                    if density_value != 0:
                        inv_key = res_args[3]
                        if inv_key in local_results_map:
                            local_results_map[inv_key] += QQ(density_value)
                        else:
                            local_results_map[inv_key] = QQ(density_value)

        orb_int_unitary_db[db_storage_key] = local_results_map
        if verbose:
            print(f"Stored {len(local_results_map)} local invariant patterns.")

    if verbose:
        print("=" * 80)
        print(f"Database update complete for D_K = {D_K}.")
        print("=" * 80)