load("orb_int_common.sage")
load("gl.sage")
load("utils.sage")
load("hermi.sage")
load("jordan.sage")
load("Lfunc.sage")
load("quadlatticeclass.sage")
load("hermilatticeclass.sage") 
load("gllatticeclass.sage") 

if 'first_run' not in locals():
    first_run = True

if first_run:
    orb_int_unitary_db = {}
    hermi_latt_db = {}  
    gl_latt_db = {}
    first_run = False


def setup_local_algebraic_data(p, cyclo_order, D_K):
    """
    Extracts local algebraic data at a prime p from the global fields (E_i/F_i) 
    and packages them into a dictionary required for local invariant computations.

    INPUT:
        p           : integer; the rational prime.
        cyclo_order : integer; the cyclotomic order m (tame part).
        D_K         : integer; the discriminant of the global quadratic field.

    OUTPUT:
        dict: A dictionary containing local algebraic structures and functions:
            - 'q', 'unif', 'E', 'OE', 'residue_field', 'conj', 'val_func',
            - 'trace_func', 'basis', 'd', 'e', 'notnorm'.
    """
    block_data = block_fields_unitary(cyclo_order, D_K, False)
    Ei = block_data["Ei"]
    Fi = block_data["Fi"]
    embed_F_to_E = block_data["embed_F_to_E"]
    
    P_Fi = Fi.primes_above(p)[0]
    q = P_Fi.norm()
    e_ram = P_Fi.ramification_index()
    
    p_in_E = Ei.ideal([embed_F_to_E(g) for g in P_Fi.gens()])
    factored_primes = list(p_in_E.factor())
    P_Ei = factored_primes[0][0]
    
    residue_field = Fi.residue_field(P_Fi)
    
    # Valuation of the relative different d
    diff_Ei = Ei.different().valuation(P_Ei)
    diff_Fi_lifted = Ei.ideal([embed_F_to_E(g) for g in Fi.different().gens()]).valuation(P_Ei)
    d = diff_Ei - diff_Fi_lifted

    # Get complex conjugation
    conj = None
    for aut in Ei.automorphisms():
        if aut(Ei.gen()) != Ei.gen():
            if all(aut(embed_F_to_E(g)) == embed_F_to_E(g) for g in Fi.gens()):
                conj = aut
                break
    if conj is None:
        conj = Ei.complex_conjugation()

    def val_func(x):
        return Ei.ideal(x).valuation(P_Ei) if x != 0 else infinity

    def trace_func(x):
        return x + conj(x)
        
    # Basis of E/F
    alpha = Ei.gen()
    if conj(alpha) == alpha:
        for g in Ei.gens():
            if conj(g) != g:
                alpha = g
                break
    basis = [Ei(1), alpha]

    # Uniformizer of the base field
    gens_F = P_Fi.gens_reduced()
    unif = None
    P_Fi_sq = P_Fi**2
    for g in gens_F:
        if g != 0 and g not in P_Fi_sq:
            unif = Fi(g)
            break

    # Non-norm element for ramified odd primes (notnorm)
    notnorm = None
    if p != 2 and len(factored_primes) == 1 and factored_primes[0][1] > 1:
        for x in Fi.ring_of_integers():
            if x not in P_Fi:
                x_mod = residue_field(x)
                if not x_mod.is_square():
                    notnorm = Fi(x)
                    break

    return {
        'q': q, 'unif': unif, 'E': Ei, 'OE': Ei.ring_of_integers(), 
        'residue_field': residue_field, 'conj': conj, 'val_func': val_func, 
        'trace_func': trace_func, 'basis': basis, 'd': d, 'e': e_ram,
        'notnorm': notnorm
    }

# ========================================================================
# Lattice Enumeration 
# ========================================================================

def enum_with_inv_hermi(p, m, mult, maxpower, D_K, alg_data):
    """
    Enumerates Hermitian lattices using generalized algebraic data.

    INPUT:
        p        : integer; the prime number.
        m        : integer; cyclotomic order (tame part).
        mult     : integer; multiplicity.
        maxpower : integer; maximum power parameter for enumeration.
        D_K      : integer; discriminant of the global quadratic field.
        alg_data : dict; dictionary containing local algebraic structures 
                   generated by setup_local_algebraic_data.

    OUTPUT:
        dict: A dictionary mapping invariant tuples (Jordan types) to lists of lattice objects.
    """
    Lattices = enum_hermi(
        alg_data['q'], p, alg_data['unif'], alg_data['E'], alg_data['OE'], 
        alg_data['residue_field'], alg_data['conj'], alg_data['val_func'], 
        alg_data['trace_func'], alg_data['basis'], alg_data['d'], alg_data['e'], 
        mult, maxpower, alg_data['notnorm']
    )
    
    result = {}
    for B in Lattices:
        lattice = B[1]
        dims = tuple(lattice.type_list)
        if dims not in result:
            result[dims] = []
        result[dims].append(lattice)
    return result

# ========================================================================
# 3. Orbital Integral Engine 
# ========================================================================

def orb_int_gl(args, Fi=None):
    """
    Engine bridge for General Linear (GL) orbital integrals.

    INPUT:
        args : list of tuples; each tuple is (p, exponent, multiplicity, max_power_param).
        Fi   : NumberField (Optional); the base totally real field.

    OUTPUT:
        list of tuples: Returns a list of (partition, value) pairs.
    """
    results = []
    for p, exponent, multiplicity, max_power_param in args:
        # Determine qv (order of the residue field of Fi)
        if Fi is not None:
            P_Fi = Fi.primes_above(p)[0]
            qv = P_Fi.norm()
        else:
            qv = p
            
        if exponent == 0:
            e = 1
        else:
            e = p**(exponent - 1) * (p - 1)
            
        max_slots = e * max_power_param
        
        # Use partitions from hermi.sage instead of the undefined enum_gl_partitions
        parts = partitions(multiplicity, max_slots)
        
        for I in parts:
            # Pass qv to ensure proper density calculation over the local field
            val = gl_mass_local_term(qv, I)
            results.append((tuple(I), val))
            
    return results

def orb_int_unitary(args_list, hermi_latt_db, D_K):
    """
    Generator that yields the total orbital integral values for unitary cases.

    INPUT:
        args_list     : list of tuples; arguments containing (p, cyclo_order, jordan_blocks, partition_tup).
        hermi_latt_db : dict; database of precomputed Hermitian lattices.
        D_K           : integer; discriminant parameter of the global field.

    OUTPUT:
        generator: Yields tuples of (args, total_orbital_integral).
    """
    for args in args_list:
        p, cyclo_order, jordan_blocks, partition_tup = args
        total_orbital_integral = 1
        max_power_param = len(jordan_blocks) - 1
        
        for i, (exponent, multiplicity) in enumerate(jordan_blocks):
            complete_order = cyclo_order * (p**exponent)
            lattice_query_key = (p, complete_order, multiplicity, max_power_param, D_K)
            target_partition = partition_tup[i]
            
            matched_lattices = hermi_latt_db[lattice_query_key][target_partition]
            
            # Multiply by the already normalized mass_local_term directly
            total_orbital_integral *= matched_lattices[0].mass_local_term
            
        yield args, total_orbital_integral

# ========================================================================
# 4. Database Update Process (Main Loop)
# ========================================================================

def update_orb_int_unitary_db(n, primes_list, D_K, pretend=False, verbose=True):
    """
    Populate orb_int_unitary_db with all local orbital integral data needed
    for elliptic finite-order stable conjugacy classes in the unitary setting.

    INPUT:
        n           : integer; total size (default global setting U(n/2,n/2))
        primes_list : list of rational primes at which local data may be needed
        D_K         : integer; discriminant parameter for E = Q(sqrt(D_K))
        pretend     : boolean; if True, only print what would be computed, do not store
        verbose     : boolean; print progress

    OUTPUT:
        None (updates the global dictionary orb_int_unitary_db in place)
    """
    
    # Properly pass D_K and verbose to match utils.sage definition
    conj_classes = conjclasses_unitary(n, primes_list, D_K, verbose)
    
    required_params = {
        (p, cyclo_order, tuple(jordan_blocks))
        for p in primes_list
        for cc in conj_classes
        for cyclo_order, jordan_blocks, _ in tot_ram_sub_conj_classes_unitary(cc, p)
    }

    new_params = [
        param for param in required_params
        if (param[0], param[1], param[2], D_K) not in orb_int_unitary_db
    ]
    num_tasks = len(new_params)
    
    if verbose:
        print("=" * 80)
        print(f"Updating unitary orbital-integral DB for D_K = {D_K}")
        print(f"Number of required local tasks: {num_tasks}")
        print("=" * 80)

    for idx, (p, cyclo_order, jordan_blocks) in enumerate(sorted(new_params), 1):
        db_storage_key = (p, cyclo_order, tuple(jordan_blocks), D_K)

        if verbose:
            print("-" * 80)
            print(f"[{idx}/{num_tasks}] Computing local data for key:")
            print(f"    p = {p}")
            print(f"    cyclo_order = {cyclo_order}")
            print(f"    jordan_blocks = {jordan_blocks}")
            print(f"    D_K = {D_K}")
            
        if pretend:
            continue

        block_data = block_fields_unitary(cyclo_order, D_K, False)
        Ei = block_data["Ei"]
        Fi = block_data["Fi"]
        
        P_Fi = Fi.primes_above(p)[0]
        is_split = (len(Ei.primes_above(P_Fi)) == 2)
        
        local_results_map = {}
        max_power_param = len(jordan_blocks) - 1

        # ============================================================
        # GL case (Split)
        # ============================================================
        if is_split:
            primes_v_above_p = Fi.primes_above(p)
            total_density_at_p = 1
            
            for v in primes_v_above_p:
                ev = v.ramification_index()
                fv = v.residue_class_degree()
                qv = p ** fv
                
                density_sums_per_block = []

                for exponent, multiplicity in jordan_blocks:
                    complete_order = cyclo_order * (p ** exponent)
                    gl_key = (v, complete_order, multiplicity, max_power_param)

                    if gl_key not in gl_latt_db:
                        gl_latt_db[gl_key] = enum_split(
                            p, complete_order, multiplicity, max_power_param, ev, qv
                        )

                    lattices_in_block = gl_latt_db[gl_key]
                    block_densities = []

                    for disc_dummy, latt_obj in lattices_in_block:
                        val = latt_obj.mass_local_term
                        block_densities.append(val)

                    density_sums_per_block.append(sum(block_densities))

                density_at_v = prod(density_sums_per_block)
                total_density_at_p *= density_at_v

            if total_density_at_p != 0:
                dummy_inv_key = tuple(Mod(0, 2) for _ in jordan_blocks)
                local_results_map[dummy_inv_key] = total_density_at_p

        # ============================================================
        # Hermitian case (Inert/Ramified)
        # ============================================================
        else:
            alg_data = setup_local_algebraic_data(p, cyclo_order, D_K)
            partition_options_per_block = []

            for exponent, multiplicity in jordan_blocks:
                complete_order = cyclo_order * (p ** exponent)
                hermi_key = (p, complete_order, multiplicity, max_power_param, D_K)

                if hermi_key not in hermi_latt_db:
                    hermi_latt_db[hermi_key] = enum_with_inv_hermi(
                        p, complete_order, multiplicity, max_power_param, D_K, alg_data
                    )

                partition_options_per_block.append(list(hermi_latt_db[hermi_key].keys()))

            for partition_combination in itertools.product(*partition_options_per_block):
                calculation_args = [(p, cyclo_order, jordan_blocks, partition_combination)]

                for result_args, density_value in orb_int_unitary(
                    calculation_args, hermi_latt_db, D_K
                ):
                    if density_value != 0:
                        inv_key = result_args[3]
                        local_results_map[inv_key] = (
                            local_results_map.get(inv_key, 0) + density_value
                        )

        orb_int_unitary_db[db_storage_key] = local_results_map

        if verbose:
            print(f"Stored {len(local_results_map)} local invariant patterns.")

    if verbose:
        print("=" * 80)
        print(f"Database update complete for D_K = {D_K}.")
        print("=" * 80)